config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  
  namespace :admin do
    resource :users
    resources :courses
    get '/dashboard', to: "dashboard#index"
    post "assign_instructor", to: "courses#assign_instructor"
  end
  
  get "students", to: "students#index"

  post "create_enrollment", to: "enrollments#create_enrollment"

  get "instructors", to: "instructors#welcome"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user

    if user.admin?
      can :manage, :all
    elsif user.instructor?
      can :read, Course
      # can :manage, Course, user_id: user.id
    elsif user.student?
      can :read, Course
      can :create, Enrollment
      can :destroy, Enrollment, user_id: user.id
    else
      can :read, Course
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :instructor, class_name: 'User',  optional: true
  has_many :enrollments
  has_many :students, through: :enrollments, source: :user
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:student, :instructor, :admin, :super_admin]

  after_initialize :set_default_role, if: :new_record?

  has_many :enrollments
  has_many :courses, through: :enrollments

  private

  def set_default_role
    self.role ||= :student
  end
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :assign_instructor]

  def index
    @courses = Course.all
  end

  def show
    @instructors = User.instructor
  end

  def new
    @course = Course.new
    authorize @course
  end

  def create
    @course = Course.new(course_params)
    authorize @course
    
    if @course.save
      redirect_to admin_courses_path, notice: 'Course was successfully created.'
    else
      render :new, notice: @course.errors.full_messages
    end
  end

  def edit
    authorize @course
  end


  def update
    if @course.update(course_params)
      authorize @course
      redirect_to admin_course_path(@course), notice: 'Course was successfully updated.'
    else
      render :edit
    end
  end

  def assign_instructor
    authorize @course
    @course.update(instructor_id: params[:id])
    redirect_to admin_courses_path, notice: 'Instructor assigned successfully.'
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description)
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
    
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    authorize @users
  end

  def show
    authorize @user
  end

  def new
    @user = User.new
    authorize @user
  end

  def edit
    authorize @user
  end

  def create
    @user = User.new(user_params)
    authorize @user
    if @user.save
      redirect_to admin_user_path(@user), notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      authorize @user
      redirect_to admin_user_path(@user), notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @user
    @user.destroy
    redirect_to admin_users_path, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected
  def after_sign_in_path_for(resource)
    case resource.role
    when "student"
      students_path
    when "admin"
      admin_dashboard_path
    when "instructor"
      instructor_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create_enrollment
    @course = Course.find(params[:course_id])
    current_user.enrollments.create(course: @course)
    redirect_to students_path, notice: 'Enrolled successfully.'
  end

  def destroy
    @enrollment = current_user.enrollments.find_by(course_id: params[:course_id])
    @enrollment.destroy
    redirect_to courses_url, notice: 'Unenrolled successfully.'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :authenticate_user!
  def welcome
    @courses = current_user.courses
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :authenticate_user!

  def index
    #TODO move code to model
    if params[:query]
      @courses = Course.where('title LIKE ?', "%#{params[:query]}%")
    else
      @courses = current_user.courses
    end
  end

  def search_courses
   
  end
end

app/helpers/admin/courses_helper.rb
module Admin::CoursesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admin/courses/_form.html.erb
<%= form_with(model: @course, url: admin_courses_path) do |form| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>
      <%= @course.errors.full_messages.inspect %>
      <ul>
        <% @course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Create Course", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/courses/edit.html.erb
<%= render 'form', course: @course %>

app/views/admin/courses/index.html.erb
<h1>Courses</h1>

<ul>
  <% @courses.each do |course| %>
    <li><%= link_to course.title, admin_course_path(course) %></li>
  <% end %>
</ul>

app/views/admin/courses/new.html.erb
<div class="container">
<h1>New course</h1>
<%= render 'form', course: @course %>
</div>

app/views/admin/courses/show.html.erb
<h1><%= @course.title %></h1>
<p><%= @course.description %></p>
<p>Assign Instructor</p>
<%= form_with(url: admin_assign_instructor_path, method: :post) do |f| %>
  <%= f.hidden_field :id, value: @course.id %>
  <%= f.collection_select :instructor_id, @instructors, :id, :name %>
  <%= f.submit "Assign Instructor" %>
<% end %>

<%= link_to "Edit", edit_admin_course_path(@course) %>

app/views/admin/dashboard/index.html.erb
<p>Hello admin</p>


<%= link_to "Create Course", new_admin_course_path %>

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control"%>
  </div>
  <div class="field">
     <%= f.label :role %><br>
    <%= f.select :role, User.roles.keys, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :password %>
   <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control"  %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form', user: @user %>

app/views/admin/users/index.html.erb
<h1>Admin - Users</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to 'Show', admin_user_path(user) %>
          <%= link_to 'Edit', edit_admin_user_path(user) %>
          <%= link_to 'Delete', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/admin/users/show.html.erb
<h1>User Details</h1>

<p><strong>ID:</strong> <%= @user.id %></p>
<p><strong>Name:</strong> <%= @user.name %></p>
<!-- Add other user attributes you want to display -->

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/home/index.html.erb
<h1>Wellcome</h1>

<%=
    link_to_if(current_user.nil?, "Login", new_user_session_path, class: 'btn btn-primary m-5') do
    link_to('Sign out', destroy_user_session_path, data: { turbo_method: :"delete" }, class: 'btn btn-danger m-5')
      end
  %>

app/views/instructors/welcome.html.erb
<h1>Courses</h1>


<table>
  <thead>
    <th>Course</th>
    <th>Discription</th>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
    <tr>
      <td><%= course.title %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseHub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <% if current_user %>
         <%= link_to('Sign out', destroy_user_session_path, data: { turbo_method: :"delete" }, class: 'btn btn-danger m-5') %>
      <% end %>
    </div>
    <div class="container">
      <%= render 'shared/flash' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/students/index.html.erb
<h1>Courses</h1>
<%= form_with(url:  students_path , method: :get) do |form| %>
  <%= form.text_field :query, placeholder: "Search for courses..." %>
  <%= form.submit "Search" %>
<% end %>

<table>
  <thead>
    <th>Course</th>
    <th>Discription</th>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
    <tr>
      <td><%= course.title %></td>
      <td><%= link_to "Enroll", create_enrollment_path(course_id: course.id), data: { 'turbo-method' => :post } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>